### ISSUE TITLE
All endpoints throw exception when using Next 11+

### ISSUE THREAD

**Issue by jonpacker** [premieroctet/next-crud#35]
When using next 11+, next-crud can't be loaded at all. For me this shows as every API endpoint throwing this error:

```
error - Error: Cannot find module 'next/dist/next-server/server/api-utils'
Require stack:
- [redacted]/node_modules/@premieroctet/next-crud/dist/httpError.js
- [redacted]/node_modules/@premieroctet/next-crud/dist/handlers/getOne.js
- [redacted]/node_modules/@premieroctet/next-crud/dist/handlers/index.js
- [redacted]/node_modules/@premieroctet/next-crud/dist/handler.js
- [redacted]/node_modules/@premieroctet/next-crud/dist/index.js
- [redacted]/.next/server/pages/api/[...nextcrud].js
- [redacted]/node_modules/next/dist/server/next-server.js
- [redacted]/node_modules/next/dist/server/next.js
- [redacted]/node_modules/next/dist/server/lib/start-server.js
- [redacted]/node_modules/next/dist/cli/next-dev.js
- [redacted]/node_modules/next/dist/bin/next
```

This is due to this pull request https://github.com/premieroctet/next-crud/pull/33 which introduces a dependency on an internal undocumented class within next—since it's internal and undocumented one can expect that they're going to move it around every now and then, and they did that in next@11. A poor fix for this would be to add next@10 to the dependencies, but IMO it's not great to be using that class in the first place. Unless the people using this library can also access the error class easily (in order to throw it), it makes the fix useless.

My suggestion for a fix would be for this module to have its own error class which users can import, rather than relying on internals of another module. This is actually the way it was before, and so the mentioned PR in my opinion only makes the situation worse.

**Comment by darmane** [comment]
Hi! I'm facing this error... I think there is a PR pending that fixes the problem. Seems to be no movement around here since February.
