### ISSUE TITLE
next-crud 2.2.0 is not compatible with Prisma 4

### ISSUE THREAD

**Issue by jberrydev** [premieroctet/next-crud#39]
If using version `2.2.0` of `next-crud` and `prisma >= 4`, you receive an error on the PrismaAdapter:  
```
Cannot convert undefined or null to object
```
Error happens here on line 5
```
import NextCrud, { PrismaAdapter } from "@premieroctet/next-crud";
import { prismaClient } from "../../server";

const handler = NextCrud({
  adapter: new PrismaAdapter({
    prismaClient: prismaClient,
  }),
});

export default handler;
```

**Comment by foyarash** [comment]
Fixed in [2.3.1](https://github.com/premieroctet/next-crud/releases/tag/v2.3.1), there is a small breaking change specified in the release note.
