### ISSUE TITLE
Use with Server-Side Rendering?

### ISSUE THREAD

**Issue by xylo04** [premieroctet/next-crud#49]
Next Crud made it really simple to expose all of my Prisma models  in API Routes, so thanks for that!

I'm thinking about moving from client-side fetches to Server Side Rendering (SSR). However, [this doc](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops-or-api-routes) suggests that API Routes and `getServerSideProps` shouldn't be used together because it's inefficient.

Does/can Next Crud provide a simple server-side API in addition to API Routes? Or should I just use the Prisma client directly at that point?

**Comment by foyarash** [comment]
I think you can simply use the Prisma client directly for that case

**Comment by xylo04** [comment]
Yeah, I guess that makes sense. Thanks!
