### ISSUE TITLE
Update documentation for Query Params: change $nin -> $notin

### ISSUE THREAD

**Issue by simonKristensen** [premieroctet/next-crud#50]
I found out the `$nin` operator in the Query Params part of the documentation is wrong, as I found it is actually called `$notin` in the codebase itself. Changing my code to use `$notin` also fixed the problem.

I'm not sure how to open a PR for an OSS project, so I'm making an issue instead.

The incorrect line can be found [here](https://github.com/premieroctet/next-crud/blob/86b6e171de3a0c37cd574dcd5c0f523e91b07fae/docs/pages/query-params.mdx?plain=1#L48)

**Comment by foyarash** [comment]
Hello

Thanks for pointing that out. It has been fixed
